# Generated by Django 3.1.5 on 2021-02-14 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210212_0907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoomImage',
        ),
    ]
