# Generated by Django 3.1.5 on 2021-02-14 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210214_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='description',
        ),
    ]
